/**
 * Cook-It step timers -- pure logic, no rendering here (components/StepTimer
 * wires this into the /cook UI). Kept independent of React so it can be
 * reused/tested on its own. TypeScript port of the old static/timer.js --
 * same behavior, typed.
 *
 * Data contract with the recipe interpreter:
 *   A step is normally a plain string. A local recipe's JSON (see
 *   src/recipes/*.json) instead gives an object for any step that needs a
 *   timer:
 *     {"text": "Hornea 40-50 minutos, hasta que...", "timer_seconds": 2700}
 *   parseStepTimerSeconds() below prefers that field the moment it's
 *   there -- recipe_engine.py's step_text() reads the same shape on the
 *   Python side wherever a step goes into spoken text or an LLM prompt.
 *   Steps generated by the LLM for a recipe with no local match are still
 *   plain strings (the model isn't asked for timer_seconds), so the regex
 *   fallback below stays in place as a safety net for those -- guessing a
 *   duration straight from the step's own Spanish text ("10 minutos",
 *   "40-50 minutos", "1 hora y media", "3 o 4 horas"...).
 */

export type Step = string | { text: string; timer_seconds?: number };

// --- Reading a duration out of a step ------------------------------------

export function stepText(step: Step | null | undefined): string {
  if (typeof step === 'string') return step;
  return step?.text ?? '';
}

const TIME_UNIT_SECONDS: Record<string, number> = {
  hora: 3600, horas: 3600, h: 3600,
  minuto: 60, minutos: 60, min: 60, mins: 60,
};

/**
 * Returns the timer duration a step needs, in whole seconds, or null if the
 * step doesn't call for one (most steps won't -- this is only for "hornea
 * 40 minutos", "deja reposar 10 minutos", "cuece 1 hora"-style steps).
 */
export function parseStepTimerSeconds(step: Step | null | undefined): number | null {
  if (step && typeof step === 'object' && typeof step.timer_seconds === 'number' && step.timer_seconds > 0) {
    return Math.round(step.timer_seconds);
  }

  const text = stepText(step).toLowerCase();

  // Range, e.g. "40-50 minutos" / "30 a 40 min" / "3 o 4 horas" -> upper
  // bound, so the timer never runs out before the dish is actually ready.
  let m = text.match(/(\d+)\s*(?:-|–|a|o)\s*(\d+)\s*(horas?|h\b|minutos?|mins?|min\b)/);
  if (m) return parseInt(m[2], 10) * (TIME_UNIT_SECONDS[m[3]] || 60);

  // "1 hora y media" / "1 hora y 30 minutos"
  m = text.match(/(\d+)\s*(horas?|h\b)\s*y\s*(media|(\d+)\s*(?:minutos?|mins?|min\b))/);
  if (m) {
    const hoursSec = parseInt(m[1], 10) * 3600;
    const extraSec = m[3] === 'media' ? 1800 : parseInt(m[4], 10) * 60;
    return hoursSec + extraSec;
  }

  // Plain "10 minutos" / "2 horas" / "45 min"
  m = text.match(/(\d+)\s*(horas?|h\b|minutos?|mins?|min\b)/);
  if (m) return parseInt(m[1], 10) * (TIME_UNIT_SECONDS[m[2]] || 60);

  return null;
}

export function hasStepTimer(step: Step | null | undefined): boolean {
  return parseStepTimerSeconds(step) !== null;
}

/** Seconds -> "mm:ss" (goes past 59:59 into "90:00" etc., no need for hh). */
export function formatTimer(totalSeconds: number): string {
  const s = Math.max(0, Math.round(totalSeconds));
  const mm = Math.floor(s / 60);
  const ss = s % 60;
  return `${mm}:${String(ss).padStart(2, '0')}`;
}

// --- The countdown itself --------------------------------------------------

// A few upbeat variants so it doesn't say the exact same line every time --
// "algo guay" as requested, not a flat "timer finished" notice.
const TIMER_FINISHED_MESSAGES = [
  '⏰ ¡Tiempo terminado! A seguir cocinando 👨‍🍳',
  '⏰ ¡Listo el tiempo! Vamos con el siguiente paso 🔥',
  '⏰ ¡Ding! Tiempo cumplido, a por el siguiente paso 🍳',
  '⏰ ¡Se acabó el tiempo! Sigamos cocinando 🥘',
];

export function randomTimerFinishedMessage(): string {
  return TIMER_FINISHED_MESSAGES[Math.floor(Math.random() * TIMER_FINISHED_MESSAGES.length)];
}

export type StepTimerState = 'idle' | 'running' | 'paused' | 'finished' | 'cancelled';

export interface StepTimerCallbacks {
  onTick?: (remainingSeconds: number, state: StepTimerState) => void;
  /** message is one of TIMER_FINISHED_MESSAGES, ready to show/speak as-is. */
  onFinish?: (message: string) => void;
}

export interface StepTimerController {
  start(): void;
  pause(): void;
  resume(): void;
  cancel(): void;
  reset(newSeconds?: number): void;
  readonly state: StepTimerState;
  readonly remainingSeconds: number;
}

/**
 * Creates a countdown timer controller. Not started automatically -- call
 * .start() (e.g. on the "poner temporizador" click).
 *
 * Uses a wall-clock end time (Date.now()-based) rather than just decrementing
 * a counter every tick, so it stays accurate even if the tab is backgrounded
 * and timers get throttled.
 */
export function createStepTimer(seconds: number, { onTick, onFinish }: StepTimerCallbacks = {}): StepTimerController {
  let remainingMs = Math.max(0, Math.round(seconds)) * 1000;
  let endAt: number | null = null; // Date.now()-space deadline while running
  let intervalId: ReturnType<typeof setInterval> | null = null;
  let state: StepTimerState = 'idle';

  function stopInterval() {
    if (intervalId !== null) {
      clearInterval(intervalId);
      intervalId = null;
    }
  }

  function tick() {
    const leftMs = Math.max(0, (endAt as number) - Date.now());
    onTick?.(Math.ceil(leftMs / 1000), state);
    if (leftMs <= 0) finish();
  }

  function finish() {
    stopInterval();
    remainingMs = 0;
    state = 'finished';
    onFinish?.(randomTimerFinishedMessage());
  }

  const controller: StepTimerController = {
    start() {
      if (state === 'running' || state === 'finished') return;
      state = 'running';
      endAt = Date.now() + remainingMs;
      tick();
      // Ticks faster than 1s so the displayed second changes right on time
      // instead of lagging behind the real deadline.
      intervalId = setInterval(tick, 250);
    },
    pause() {
      if (state !== 'running') return;
      remainingMs = Math.max(0, (endAt as number) - Date.now());
      stopInterval();
      state = 'paused';
      onTick?.(Math.ceil(remainingMs / 1000), state);
    },
    resume() {
      controller.start();
    },
    cancel() {
      stopInterval();
      state = 'cancelled';
    },
    reset(newSeconds: number = seconds) {
      stopInterval();
      remainingMs = Math.max(0, Math.round(newSeconds)) * 1000;
      state = 'idle';
      onTick?.(Math.ceil(remainingMs / 1000), state);
    },
    get state() {
      return state;
    },
    get remainingSeconds() {
      return state === 'running'
        ? Math.ceil(Math.max(0, (endAt as number) - Date.now()) / 1000)
        : Math.ceil(remainingMs / 1000);
    },
  };

  return controller;
}
